default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  data_schema: teneo
  pwd_schema: teneo_password
  schema_search_path: teneo, teneo_password, public

  username: teneo
  password: teneo

  dba_name: teneo_dba
  dba_pass: teneo_dba

  pwd_name: teneo_password
  pwd_pass: teneo_password

  migrations_paths:
    - <%= Teneo::DataModel.migrations_path %>
    - "db/migrate"

development:
  <<: *default
  host: localhost
  port: 5432
  database: teneo_dev

test:
  <<: *default
  host: localhost
  port: 5432
  database: ingester_test

production:
  <<: *default
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] || 'teneo' %>
  port: <%= ENV['DATABASE_PORT']&.to_i || 5432 %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  dba_name: <%= ENV['DATABASE_DBA_USERNAME'] %>
  dba_pass: <%= ENV['DATABASE_DBA_PASSWORD'] %>

